### ISSUE TITLE
Error when selecting a Druid datasource

### ISSUE THREAD

**Issue by rschindlauer** [grafadruid/druid-grafana#115]
I was able to add the plugin (v1.2.0) and create a Druid datasource, but as soon as I select it on a dashboard, I get an error:
```
An unexpected error happened
Details
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at eval (https://myserver:4000/public/plugins/grafadruid-druid-datasource/module.js:2:780517)
    at t (https://myserver:4000/public/build/app.63a9c1d648180e457252.js:2:1910828)
    at t (https://myserver:4000/public/build/app.63a9c1d648180e457252.js:2:1911358)
    [...]
```

**Comment by jbguerraz** [comment]
Hello @rschindlauer 
How did you install the plugin ?
Thank you!

**Comment by jbguerraz** [comment]
Hello @rschindlauer 
Is that issue still active ?

**Comment by rschindlauer** [comment]
> Hello @rschindlauer Is that issue still active ?

I haven't tried any further. You can close it.

**Comment by jbguerraz** [comment]
Ok. Feel free to re-open if the need resurge
